# Generated by Django 2.2.5 on 2020-07-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workstand',
            fields=[
                ('ws_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
