# Generated by Django 2.2.5 on 2020-07-13 11:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceplanner', '0002_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('us_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='spaceplanner.User')),
                ('window', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('noise', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(5)])),
                ('large_screen', models.BooleanField(default=False)),
                ('is_mac', models.BooleanField(default=False)),
            ],
        ),
    ]
