# Generated by Django 2.2.5 on 2020-07-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceplanner', '0003_preference_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workweek',
            fields=[
                ('start_date', models.DateField(primary_key=True, serialize=False)),
                ('monday', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday', to='spaceplanner.User')),
                ('tuesday', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday', to='spaceplanner.User')),
                ('workstand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceplanner.Workstand')),
            ],
        ),
    ]
