# Generated by Django 2.2.5 on 2020-07-13 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceplanner', '0004_workweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='workweek',
            name='friday',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday', to='spaceplanner.User'),
        ),
        migrations.AddField(
            model_name='workweek',
            name='saturday',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saturday', to='spaceplanner.User'),
        ),
        migrations.AddField(
            model_name='workweek',
            name='sunday',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday', to='spaceplanner.User'),
        ),
        migrations.AddField(
            model_name='workweek',
            name='thursday',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday', to='spaceplanner.User'),
        ),
        migrations.AddField(
            model_name='workweek',
            name='wednesday',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday', to='spaceplanner.User'),
        ),
    ]
