# Generated by Django 2.2.5 on 2020-07-15 12:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('ws_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('window', models.BooleanField(default=False)),
                ('noise', models.BooleanField(default=False)),
                ('large_screen', models.BooleanField(default=False)),
                ('is_mac', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('us_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('favourite_workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spaceplanner.Workstation')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.BooleanField(default=False)),
                ('window_preference', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('noise', models.BooleanField(default=False)),
                ('noise_preference', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('large_screen', models.BooleanField(default=False)),
                ('large_screen_preference', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('is_mac', models.BooleanField(default=False)),
                ('is_mac_preference', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='spaceplanner.User')),
            ],
        ),
        migrations.CreateModel(
            name='Workweek',
            fields=[
                ('week_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('friday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday', to='spaceplanner.User')),
                ('monday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday', to='spaceplanner.User')),
                ('saturday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saturday', to='spaceplanner.User')),
                ('sunday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday', to='spaceplanner.User')),
                ('thursday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday', to='spaceplanner.User')),
                ('tuesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday', to='spaceplanner.User')),
                ('wednesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday', to='spaceplanner.User')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceplanner.Workstation')),
            ],
            options={
                'unique_together': {('workstation', 'start_date')},
            },
        ),
    ]
