# Generated by Django 2.2.5 on 2020-07-16 09:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import spaceplanner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('us_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, verbose_name='username')),
            ],
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('ws_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SGWorkstationPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.BooleanField(default=False, verbose_name='window')),
                ('noise', models.BooleanField(default=False, verbose_name='noise')),
                ('large_screen', models.BooleanField(default=False, verbose_name='large_screen')),
                ('is_mac', models.BooleanField(default=False, verbose_name='is_mac')),
                ('workstation', models.ForeignKey(on_delete=spaceplanner.models.Workstation, to='spaceplanner.Workstation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SGEmployeePreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.BooleanField(default=False, verbose_name='window')),
                ('window_preference', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='window_preference')),
                ('noise', models.BooleanField(default=False, verbose_name='noise')),
                ('noise_preference', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='noise_preference')),
                ('large_screen', models.BooleanField(default=False, verbose_name='large_screen')),
                ('large_screen_preference', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='large_screen_preference')),
                ('is_mac', models.BooleanField(default=False, verbose_name='is_mac')),
                ('is_mac_preference', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='is_mac_preference')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceplanner.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='favourite_workspace',
            field=models.ManyToManyField(to='spaceplanner.Workstation'),
        ),
        migrations.CreateModel(
            name='Workweek',
            fields=[
                ('week_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('friday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday', to='spaceplanner.Employee')),
                ('monday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday', to='spaceplanner.Employee')),
                ('saturday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saturday', to='spaceplanner.Employee')),
                ('sunday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday', to='spaceplanner.Employee')),
                ('thursday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday', to='spaceplanner.Employee')),
                ('tuesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday', to='spaceplanner.Employee')),
                ('wednesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday', to='spaceplanner.Employee')),
                ('workstation', models.ForeignKey(on_delete=spaceplanner.models.Workstation, to='spaceplanner.Workstation')),
            ],
            options={
                'unique_together': {('workstation', 'start_date')},
            },
        ),
    ]
