# Generated by Django 2.2.5 on 2020-07-17 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaceplanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SGEmployeePreferences',
            new_name='EmployeePreferences',
        ),
        migrations.RenameModel(
            old_name='SGWorkstationPreferences',
            new_name='WorkstationPreferences',
        ),
        migrations.AlterField(
            model_name='employeepreferences',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workweek',
            name='friday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workweek',
            name='monday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workweek',
            name='saturday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saturday', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workweek',
            name='sunday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workweek',
            name='thursday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workweek',
            name='tuesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workweek',
            name='wednesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
