# Generated by Django 2.2.5 on 2020-07-16 09:14

from django.db import migrations, models
import spaceplanner.models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgemployeepreferences',
            name='employee',
            field=models.ForeignKey(on_delete=spaceplanner.models.Employee, to='spaceplanner.Employee'),
        ),
    ]
