# Generated by Django 2.2.5 on 2020-07-22 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaceplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepreferences',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workstationpreferences',
            name='workstation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spaceplanner.Workstation'),
        ),
        migrations.AlterUniqueTogether(
            name='userweek',
            unique_together={('employee', 'year', 'week')},
        ),
    ]
