# Generated by Django 2.2.5 on 2020-07-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceplanner', '0002_auto_20200717_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepreferences',
            name='favourite_workspace',
            field=models.ManyToManyField(to='spaceplanner.Workstation'),
        ),
    ]
