# Generated by Django 2.2.5 on 2020-08-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceplanner', '0002_auto_20200724_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepreferences',
            name='favourite_workspace',
            field=models.ManyToManyField(blank=True, default=None, to='spaceplanner.Workstation'),
        ),
    ]
