# Generated by Django 2.2.5 on 2020-07-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceplanner', '0003_auto_20200716_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workweek',
            old_name='start_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='sgemployeepreferences',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceplanner.Employee'),
        ),
        migrations.AlterField(
            model_name='sgworkstationpreferences',
            name='workstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceplanner.Workstation'),
        ),
        migrations.AlterUniqueTogether(
            name='workweek',
            unique_together={('workstation', 'date')},
        ),
    ]
