# Generated by Django 2.2.5 on 2020-08-06 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceplanner', '0003_auto_20200806_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepreferences',
            name='large_screen_preference',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Largescreen priority'),
        ),
    ]
