# Generated by Django 2.2.5 on 2020-07-17 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spaceplanner', '0004_userweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='userweek',
            name='monday_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='monday_date'),
            preserve_default=False,
        ),
    ]
