# Generated by Django 2.2.5 on 2020-08-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceplanner', '0005_auto_20200813_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='label',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
