# Generated by Django 2.2.5 on 2020-08-14 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceplanner', '0006_auto_20200813_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepreferences',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='employeepreferences',
            name='favourite_workspace',
            field=models.ManyToManyField(blank=True, default=None, to='spaceplanner.Workstation', verbose_name='favourite_workspace'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='label',
            field=models.CharField(max_length=100, unique=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='workstationpreferences',
            name='workstation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spaceplanner.Workstation', verbose_name='workstation'),
        ),
    ]
