# Generated by Django 2.2.5 on 2020-08-18 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceplanner', '0008_auto_20200818_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepreferences',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_preferences', to=settings.AUTH_USER_MODEL, verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='workstationpreferences',
            name='workstation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workstation_preferences', to='spaceplanner.Workstation', verbose_name='workstation'),
        ),
        migrations.AlterField(
            model_name='workweek',
            name='workstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workweeks', to='spaceplanner.Workstation', verbose_name='workstation'),
        ),
    ]
